# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20161103_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
